name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build Exe
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Exe
        uses: actions/upload-artifact@v4
        with:
          name: steam-ticket-generator
          path: target/x86_64-pc-windows-msvc/release/*.exe
